Log into RH container registry before pushing

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -50,9 +50,15 @@ if [ "$git_description" = "v${VERSION}" ]; then
   echo "Tagging and pushing ${REDHAT_IMAGE}"
 
   docker tag "secretless-broker-redhat:${FULL_VERSION_TAG}" "${REDHAT_IMAGE}:${VERSION}"
-  # you can't push the same tag twice to redhat registry, so ignore errors
-  if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
-    echo 'RedHat push FAILED! (Maybe the image was pushed already?)'
-    exit 0
+
+  if docker login scan.connect.redhat.com -u unused -p "${REDHAT_API_KEY}"; then
+    # you can't push the same tag twice to redhat registry, so ignore errors
+    if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
+      echo 'RedHat push FAILED! (maybe the image was pushed already?)'
+      exit 0
+    fi
+  else
+    echo 'Failed to log in to scan.connect.redhat.com'
+    exit 1
   fi
 fi
