Correctly identify failing builds (#60)
* Clean up and added error checking to build/build

Old code would eat errors of builds, hiding any issues that we might be
having. The new code now checks for exit codes, prints the commands being
executed, and dumps the list of failed builds afterwards.

In the process, CGO has now been enabled and i386 arch target removed.

* Slim down our dev Dockerfile

Each RUN command adds a new layer, increasing the build size and
layer accounting needs so we flattened the layers up.
(See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers
for more details about this)

Also, since our system packages are less likely to change rather than
our deps, we now install them first to minimize cache busting

(See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#build-cache
for more details about this)

* Removed darwin and windows default builds

Sinc we don't have a full toolchain in the container and we use CGO in
parts fo the keyring management, we have decided to nix the OSX/Win
builds for now.

diff --git a/build/build b/build/build
--- a/build/build
+++ b/build/build
@@ -20,8 +20,8 @@ trap on_exit EXIT
 
 readonly VERSION="$(cat VERSION)"
 readonly GOLANG_VERSION="1.10"
-readonly SUPPORTED_BUILD_OS="windows darwin linux"
-readonly SUPPORTED_BUILD_ARCH="386 amd64"
+readonly SUPPORTED_BUILD_OS="linux"
+readonly SUPPORTED_BUILD_ARCH="amd64"
 readonly REPOSITORY="github.com/conjurinc/secretless"
 readonly CONTAINER_ID="$(docker run \
   -v "$(pwd):/go/src/${REPOSITORY}" \
@@ -33,21 +33,47 @@ readonly CONTAINER_ID="$(docker run \
 BUILD_OS="${1:-${SUPPORTED_BUILD_OS}}"
 BUILD_ARCH="${2:-${SUPPORTED_BUILD_ARCH}}"
 
-docker exec "${CONTAINER_ID}" bash -c "
+
+docker exec "${CONTAINER_ID}" bash -exc "
   cd /go/src/${REPOSITORY}
-  curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
+  curl -s https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
   dep ensure
+
+  failed_builds=()
 
   for GOOS in ${BUILD_OS}; do
     for GOARCH in ${BUILD_ARCH}; do
       export GOOS
       export GOARCH
+
+      export CGO_ENABLED=1
+
       echo \"Building binaries for \${GOOS} \${GOARCH}\"
       mkdir -p bin/\${GOOS}/\${GOARCH}
-      go build -o bin/\${GOOS}/\${GOARCH}/secretless ./cmd/secretless
-      go build -o bin/\${GOOS}/\${GOARCH}/summon2 ./cmd/summon2
+
+      for app in secretless summon2; do
+        app_build=\"\${GOOS}/\${GOARCH}/\${app}\"
+        echo \" - Building \${app_build}...\"
+        if ! go build -o bin/\${app_build} ./cmd/\${app}; then
+          echo \"Error building \${app_build}!\" 2>&1
+          failed_builds+=(\$app_build)
+          break
+        fi
+
+        echo \"\${app_build} build success!\"
+      done
     done
   done
+
+  # Show all failed builds if we had any
+  if [ \${#failed_builds[@]} -ne 0 ]; then
+    echo \"Build failures:\"
+    for failed_build in \${failed_builds[@]}; do
+      echo \" - \${failed_build}\"
+    done
+
+    exit 1
+  fi
 "
 
 echo "Building Docker images"
