Made our containers have secretless binary in the $PATH
This should allow easy running if we don't use the default entrypoint.

diff --git a/build/test b/build/test
--- a/build/test
+++ b/build/test
@@ -1,55 +1,55 @@
 #!/bin/bash
 
-set -exo pipefail
+set -eo pipefail
 
 project_dir=$PWD
 rm -f $project_dir/test/junit.output
 touch $project_dir/test/junit.output
 
-cd test
-
-exit_status="0"
-for dir in */; do
-  pushd "$dir" 2>/dev/null
-    # Bail if the folder doesn't have a start script
-    if [[ ! -f start ]]; then
-      popd 2>/dev/null
-      continue
-    fi
-
-    # Stop anything that might be running
-    if [[ -f ./stop ]]; then
-      ./stop || true
-    fi
-
-    # Start the needed prerequisites
-    ./start
-
-    # Run the tests
-    set +e
-      ./test | tee -a $project_dir/test/junit.output
-      last_status="$?"
-
-      # Only save first failure exit code
-      if [[ "$exit_status" -eq "0" && "$last_status" -ne "0" ]]; then
-        exit_status="$last_status"
+pushd test
+  exit_status="0"
+  for dir in */; do
+    pushd "$dir" 2>/dev/null
+      # Bail if the folder doesn't have a start script
+      if [[ ! -f start ]]; then
+        popd 2>/dev/null
+        continue
       fi
-    set -e
 
-    # Clean up
-    if [[ -f ./stop ]]; then
-      ./stop
-    fi
-  popd
-done
+      # Stop anything that might be running
+      if [[ -f ./stop ]]; then
+        ./stop || true
+      fi
 
-rm -f $project_dir/test/junit.xml
-docker run --rm \
-  -v $project_dir/test/:/go/src/github.com/conjurinc/secretless/test/output/ \
-  secretless-dev \
-  bash -exc "
-    go get -u github.com/jstemmer/go-junit-report
-    cat ./test/output/junit.output | go-junit-report > ./test/output/junit.xml
-  "
+      # Start the needed prerequisites
+      ./start
+
+      # Run the tests
+      set +e
+        ./test | tee -a $project_dir/test/junit.output
+        last_status="$?"
+
+        # Only save first failure exit code
+        if [[ "$exit_status" -eq "0" && "$last_status" -ne "0" ]]; then
+          exit_status="$last_status"
+        fi
+      set -e
+
+      # Clean up
+      if [[ -f ./stop ]]; then
+        ./stop
+      fi
+    popd
+  done
+
+  rm -f $project_dir/test/junit.xml
+  docker run --rm \
+    -v $project_dir/test/:/go/src/github.com/conjurinc/secretless/test/output/ \
+    secretless-dev \
+    bash -exc "
+      go get -u github.com/jstemmer/go-junit-report
+      cat ./test/output/junit.output | go-junit-report > ./test/output/junit.xml
+    "
+popd || true
 
 exit $exit_status
